// flow-typed signature: 14e9b34c04042a67e37c826cc6174628
// flow-typed version: <<STUB>>/bristol_v^0.3.3/flow_v0.52.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'bristol'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'bristol' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'bristol/lib/Bristol' {
  declare module.exports: any;
}

declare module 'bristol/lib/formatters/commonInfoModel' {
  declare module.exports: any;
}

declare module 'bristol/lib/formatters/human' {
  declare module.exports: any;
}

declare module 'bristol/lib/formatters/json' {
  declare module.exports: any;
}

declare module 'bristol/lib/formatters/syslog' {
  declare module.exports: any;
}

declare module 'bristol/lib/targets/console' {
  declare module.exports: any;
}

declare module 'bristol/lib/targets/file' {
  declare module.exports: any;
}

declare module 'bristol/lib/targets/loggly' {
  declare module.exports: any;
}

declare module 'bristol/lib/Util' {
  declare module.exports: any;
}

declare module 'bristol/test/Bristol' {
  declare module.exports: any;
}

declare module 'bristol/test/formatters/commonInfoModel' {
  declare module.exports: any;
}

declare module 'bristol/test/formatters/human' {
  declare module.exports: any;
}

declare module 'bristol/test/formatters/json' {
  declare module.exports: any;
}

declare module 'bristol/test/formatters/syslog' {
  declare module.exports: any;
}

declare module 'bristol/test/targets/console' {
  declare module.exports: any;
}

declare module 'bristol/test/targets/file' {
  declare module.exports: any;
}

declare module 'bristol/test/targets/loggly' {
  declare module.exports: any;
}

declare module 'bristol/test/Util' {
  declare module.exports: any;
}

// Filename aliases
declare module 'bristol/lib/Bristol.js' {
  declare module.exports: $Exports<'bristol/lib/Bristol'>;
}
declare module 'bristol/lib/formatters/commonInfoModel.js' {
  declare module.exports: $Exports<'bristol/lib/formatters/commonInfoModel'>;
}
declare module 'bristol/lib/formatters/human.js' {
  declare module.exports: $Exports<'bristol/lib/formatters/human'>;
}
declare module 'bristol/lib/formatters/json.js' {
  declare module.exports: $Exports<'bristol/lib/formatters/json'>;
}
declare module 'bristol/lib/formatters/syslog.js' {
  declare module.exports: $Exports<'bristol/lib/formatters/syslog'>;
}
declare module 'bristol/lib/targets/console.js' {
  declare module.exports: $Exports<'bristol/lib/targets/console'>;
}
declare module 'bristol/lib/targets/file.js' {
  declare module.exports: $Exports<'bristol/lib/targets/file'>;
}
declare module 'bristol/lib/targets/loggly.js' {
  declare module.exports: $Exports<'bristol/lib/targets/loggly'>;
}
declare module 'bristol/lib/Util.js' {
  declare module.exports: $Exports<'bristol/lib/Util'>;
}
declare module 'bristol/test/Bristol.js' {
  declare module.exports: $Exports<'bristol/test/Bristol'>;
}
declare module 'bristol/test/formatters/commonInfoModel.js' {
  declare module.exports: $Exports<'bristol/test/formatters/commonInfoModel'>;
}
declare module 'bristol/test/formatters/human.js' {
  declare module.exports: $Exports<'bristol/test/formatters/human'>;
}
declare module 'bristol/test/formatters/json.js' {
  declare module.exports: $Exports<'bristol/test/formatters/json'>;
}
declare module 'bristol/test/formatters/syslog.js' {
  declare module.exports: $Exports<'bristol/test/formatters/syslog'>;
}
declare module 'bristol/test/targets/console.js' {
  declare module.exports: $Exports<'bristol/test/targets/console'>;
}
declare module 'bristol/test/targets/file.js' {
  declare module.exports: $Exports<'bristol/test/targets/file'>;
}
declare module 'bristol/test/targets/loggly.js' {
  declare module.exports: $Exports<'bristol/test/targets/loggly'>;
}
declare module 'bristol/test/Util.js' {
  declare module.exports: $Exports<'bristol/test/Util'>;
}
