// flow-typed signature: df62a43786ff6a9a8d7277ccffc4da90
// flow-typed version: <<STUB>>/express-react-views_v^0.10.2/flow_v0.52.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'express-react-views'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'express-react-views' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'express-react-views/test/es5-component' {
  declare module.exports: any;
}

declare module 'express-react-views/test/es6-component' {
  declare module.exports: any;
}

declare module 'express-react-views/test/es6-flow-component' {
  declare module.exports: any;
}

declare module 'express-react-views/test/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'express-react-views/index' {
  declare module.exports: $Exports<'express-react-views'>;
}
declare module 'express-react-views/index.js' {
  declare module.exports: $Exports<'express-react-views'>;
}
declare module 'express-react-views/test/es5-component.jsx' {
  declare module.exports: $Exports<'express-react-views/test/es5-component'>;
}
declare module 'express-react-views/test/es6-component.jsx' {
  declare module.exports: $Exports<'express-react-views/test/es6-component'>;
}
declare module 'express-react-views/test/es6-flow-component.jsx' {
  declare module.exports: $Exports<'express-react-views/test/es6-flow-component'>;
}
declare module 'express-react-views/test/index.js' {
  declare module.exports: $Exports<'express-react-views/test/index'>;
}
