// flow-typed signature: b6e9c596b16bfcb7d9b625d85e39a292
// flow-typed version: <<STUB>>/gulp-imagemin_v3.0.3/flow_v0.52.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gulp-imagemin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'gulp-imagemin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'gulp-imagemin/index' {
  declare module.exports: $Exports<'gulp-imagemin'>;
}
declare module 'gulp-imagemin/index.js' {
  declare module.exports: $Exports<'gulp-imagemin'>;
}
