// flow-typed signature: 2af01ff280604dd8dc3bbd13c9ef571a
// flow-typed version: <<STUB>>/gulp-polyfiller_v0.0.1/flow_v0.52.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gulp-polyfiller'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'gulp-polyfiller' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'gulp-polyfiller/gulpfile' {
  declare module.exports: any;
}

declare module 'gulp-polyfiller/polyfills/polyfills' {
  declare module.exports: any;
}

declare module 'gulp-polyfiller/tests/index' {
  declare module.exports: any;
}

declare module 'gulp-polyfiller/utils/logger' {
  declare module.exports: any;
}

// Filename aliases
declare module 'gulp-polyfiller/gulpfile.js' {
  declare module.exports: $Exports<'gulp-polyfiller/gulpfile'>;
}
declare module 'gulp-polyfiller/index' {
  declare module.exports: $Exports<'gulp-polyfiller'>;
}
declare module 'gulp-polyfiller/index.js' {
  declare module.exports: $Exports<'gulp-polyfiller'>;
}
declare module 'gulp-polyfiller/polyfills/polyfills.js' {
  declare module.exports: $Exports<'gulp-polyfiller/polyfills/polyfills'>;
}
declare module 'gulp-polyfiller/tests/index.js' {
  declare module.exports: $Exports<'gulp-polyfiller/tests/index'>;
}
declare module 'gulp-polyfiller/utils/logger.js' {
  declare module.exports: $Exports<'gulp-polyfiller/utils/logger'>;
}
