// flow-typed signature: d4c2d4499ab0be1e083c2e5f0cd339c4
// flow-typed version: <<STUB>>/gulp-htmlhint_v0.3.1/flow_v0.52.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gulp-htmlhint'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'gulp-htmlhint' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'gulp-htmlhint/test/main' {
  declare module.exports: any;
}

// Filename aliases
declare module 'gulp-htmlhint/index' {
  declare module.exports: $Exports<'gulp-htmlhint'>;
}
declare module 'gulp-htmlhint/index.js' {
  declare module.exports: $Exports<'gulp-htmlhint'>;
}
declare module 'gulp-htmlhint/test/main.js' {
  declare module.exports: $Exports<'gulp-htmlhint/test/main'>;
}
