// flow-typed signature: 0064bdca9590350e747ffa70997b65df
// flow-typed version: <<STUB>>/gulp-scss-lint_v0.4.0/flow_v0.52.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gulp-scss-lint'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'gulp-scss-lint' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'gulp-scss-lint/src/checkstyle' {
  declare module.exports: any;
}

declare module 'gulp-scss-lint/src/command' {
  declare module.exports: any;
}

declare module 'gulp-scss-lint/src/index' {
  declare module.exports: any;
}

declare module 'gulp-scss-lint/src/reporters' {
  declare module.exports: any;
}

declare module 'gulp-scss-lint/src/scss-lint' {
  declare module.exports: any;
}

declare module 'gulp-scss-lint/test/main' {
  declare module.exports: any;
}

declare module 'gulp-scss-lint/test/reporters' {
  declare module.exports: any;
}

// Filename aliases
declare module 'gulp-scss-lint/src/checkstyle.js' {
  declare module.exports: $Exports<'gulp-scss-lint/src/checkstyle'>;
}
declare module 'gulp-scss-lint/src/command.js' {
  declare module.exports: $Exports<'gulp-scss-lint/src/command'>;
}
declare module 'gulp-scss-lint/src/index.js' {
  declare module.exports: $Exports<'gulp-scss-lint/src/index'>;
}
declare module 'gulp-scss-lint/src/reporters.js' {
  declare module.exports: $Exports<'gulp-scss-lint/src/reporters'>;
}
declare module 'gulp-scss-lint/src/scss-lint.js' {
  declare module.exports: $Exports<'gulp-scss-lint/src/scss-lint'>;
}
declare module 'gulp-scss-lint/test/main.js' {
  declare module.exports: $Exports<'gulp-scss-lint/test/main'>;
}
declare module 'gulp-scss-lint/test/reporters.js' {
  declare module.exports: $Exports<'gulp-scss-lint/test/reporters'>;
}
