// flow-typed signature: b2f44b177cfc44c80f8de60e748ff0fe
// flow-typed version: <<STUB>>/gulp-inject_v4.1.0/flow_v0.52.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gulp-inject'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'gulp-inject' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'gulp-inject/src/extname/index' {
  declare module.exports: any;
}

declare module 'gulp-inject/src/inject/index' {
  declare module.exports: any;
}

declare module 'gulp-inject/src/path/index' {
  declare module.exports: any;
}

declare module 'gulp-inject/src/path/path_test' {
  declare module.exports: any;
}

declare module 'gulp-inject/src/tags/index' {
  declare module.exports: any;
}

declare module 'gulp-inject/src/transform/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'gulp-inject/index' {
  declare module.exports: $Exports<'gulp-inject'>;
}
declare module 'gulp-inject/index.js' {
  declare module.exports: $Exports<'gulp-inject'>;
}
declare module 'gulp-inject/src/extname/index.js' {
  declare module.exports: $Exports<'gulp-inject/src/extname/index'>;
}
declare module 'gulp-inject/src/inject/index.js' {
  declare module.exports: $Exports<'gulp-inject/src/inject/index'>;
}
declare module 'gulp-inject/src/path/index.js' {
  declare module.exports: $Exports<'gulp-inject/src/path/index'>;
}
declare module 'gulp-inject/src/path/path_test.js' {
  declare module.exports: $Exports<'gulp-inject/src/path/path_test'>;
}
declare module 'gulp-inject/src/tags/index.js' {
  declare module.exports: $Exports<'gulp-inject/src/tags/index'>;
}
declare module 'gulp-inject/src/transform/index.js' {
  declare module.exports: $Exports<'gulp-inject/src/transform/index'>;
}
