// flow-typed signature: af5b14bc78c30db482e32d32de556041
// flow-typed version: <<STUB>>/gulp-ssh_v0.6.0/flow_v0.52.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gulp-ssh'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'gulp-ssh' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'gulp-ssh/debug/index' {
  declare module.exports: any;
}

declare module 'gulp-ssh/gulpfile' {
  declare module.exports: any;
}

declare module 'gulp-ssh/test/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'gulp-ssh/debug/index.js' {
  declare module.exports: $Exports<'gulp-ssh/debug/index'>;
}
declare module 'gulp-ssh/gulpfile.js' {
  declare module.exports: $Exports<'gulp-ssh/gulpfile'>;
}
declare module 'gulp-ssh/index' {
  declare module.exports: $Exports<'gulp-ssh'>;
}
declare module 'gulp-ssh/index.js' {
  declare module.exports: $Exports<'gulp-ssh'>;
}
declare module 'gulp-ssh/test/index.js' {
  declare module.exports: $Exports<'gulp-ssh/test/index'>;
}
