// flow-typed signature: 8c1b81c85ca88c24b8b3b6140b6d8e69
// flow-typed version: <<STUB>>/loggly_v^1.1.1/flow_v0.52.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'loggly'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'loggly' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'loggly/lib/loggly' {
  declare module.exports: any;
}

declare module 'loggly/lib/loggly/client' {
  declare module.exports: any;
}

declare module 'loggly/lib/loggly/common' {
  declare module.exports: any;
}

declare module 'loggly/lib/loggly/search' {
  declare module.exports: any;
}

declare module 'loggly/test/common-test' {
  declare module.exports: any;
}

declare module 'loggly/test/customer-test' {
  declare module.exports: any;
}

declare module 'loggly/test/helpers' {
  declare module.exports: any;
}

declare module 'loggly/test/log-test' {
  declare module.exports: any;
}

declare module 'loggly/test/search-test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'loggly/lib/loggly.js' {
  declare module.exports: $Exports<'loggly/lib/loggly'>;
}
declare module 'loggly/lib/loggly/client.js' {
  declare module.exports: $Exports<'loggly/lib/loggly/client'>;
}
declare module 'loggly/lib/loggly/common.js' {
  declare module.exports: $Exports<'loggly/lib/loggly/common'>;
}
declare module 'loggly/lib/loggly/search.js' {
  declare module.exports: $Exports<'loggly/lib/loggly/search'>;
}
declare module 'loggly/test/common-test.js' {
  declare module.exports: $Exports<'loggly/test/common-test'>;
}
declare module 'loggly/test/customer-test.js' {
  declare module.exports: $Exports<'loggly/test/customer-test'>;
}
declare module 'loggly/test/helpers.js' {
  declare module.exports: $Exports<'loggly/test/helpers'>;
}
declare module 'loggly/test/log-test.js' {
  declare module.exports: $Exports<'loggly/test/log-test'>;
}
declare module 'loggly/test/search-test.js' {
  declare module.exports: $Exports<'loggly/test/search-test'>;
}
