// flow-typed signature: f9f362e50ef2dd088a465ca42b9a4224
// flow-typed version: <<STUB>>/scss-lint_v0.0.0/flow_v0.52.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'scss-lint'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'scss-lint' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'scss-lint/bin/scss-lint' {
  declare module.exports: any;
}

declare module 'scss-lint/lib/cli' {
  declare module.exports: any;
}

declare module 'scss-lint/lib/lint' {
  declare module.exports: any;
}

declare module 'scss-lint/lib/linter/bang_format' {
  declare module.exports: any;
}

declare module 'scss-lint/lib/linter/border_zero' {
  declare module.exports: any;
}

declare module 'scss-lint/lib/linter/color_keyword' {
  declare module.exports: any;
}

declare module 'scss-lint/lib/linter/color_variable' {
  declare module.exports: any;
}

declare module 'scss-lint/lib/linter/comment' {
  declare module.exports: any;
}

declare module 'scss-lint/lib/linter/compass_property_with_mixin' {
  declare module.exports: any;
}

declare module 'scss-lint/lib/linter/compass' {
  declare module.exports: any;
}

declare module 'scss-lint/lib/linter/debug_statement' {
  declare module.exports: any;
}

declare module 'scss-lint/lib/linter/declaration_order' {
  declare module.exports: any;
}

declare module 'scss-lint/lib/linter/duplicate_property' {
  declare module.exports: any;
}

declare module 'scss-lint/lib/linter/else_placement' {
  declare module.exports: any;
}

declare module 'scss-lint/lib/linter/empty_line_between_blocks' {
  declare module.exports: any;
}

declare module 'scss-lint/lib/linter/empty_rule' {
  declare module.exports: any;
}

declare module 'scss-lint/lib/linter/final_newline' {
  declare module.exports: any;
}

declare module 'scss-lint/lib/linter/hex_length' {
  declare module.exports: any;
}

declare module 'scss-lint/lib/linter/hex_notation' {
  declare module.exports: any;
}

declare module 'scss-lint/lib/linter/hex_validation' {
  declare module.exports: any;
}

declare module 'scss-lint/lib/linter/id_selector' {
  declare module.exports: any;
}

declare module 'scss-lint/lib/linter/import_path' {
  declare module.exports: any;
}

declare module 'scss-lint/lib/linter/important_rule' {
  declare module.exports: any;
}

declare module 'scss-lint/lib/linter/indentation' {
  declare module.exports: any;
}

declare module 'scss-lint/lib/linter/index' {
  declare module.exports: any;
}

declare module 'scss-lint/lib/linter/leading_zero' {
  declare module.exports: any;
}

declare module 'scss-lint/lib/linter/mergeable_selector' {
  declare module.exports: any;
}

declare module 'scss-lint/lib/linter/name_format' {
  declare module.exports: any;
}

declare module 'scss-lint/lib/linter/nesting_depth' {
  declare module.exports: any;
}

declare module 'scss-lint/lib/linter/placeholder_in_extend' {
  declare module.exports: any;
}

declare module 'scss-lint/lib/linter/property_count' {
  declare module.exports: any;
}

declare module 'scss-lint/lib/linter/property_sort_order' {
  declare module.exports: any;
}

declare module 'scss-lint/lib/linter/property_spelling' {
  declare module.exports: any;
}

declare module 'scss-lint/lib/linter/qualifying_element' {
  declare module.exports: any;
}

declare module 'scss-lint/lib/linter/selector_depth' {
  declare module.exports: any;
}

declare module 'scss-lint/lib/linter/selector_format' {
  declare module.exports: any;
}

declare module 'scss-lint/lib/linter/shorthand' {
  declare module.exports: any;
}

declare module 'scss-lint/lib/linter/single_line_per_property' {
  declare module.exports: any;
}

declare module 'scss-lint/lib/linter/single_line_per_selector' {
  declare module.exports: any;
}

declare module 'scss-lint/lib/linter/space_after_comma' {
  declare module.exports: any;
}

declare module 'scss-lint/lib/linter/space_after_property_colon' {
  declare module.exports: any;
}

declare module 'scss-lint/lib/linter/space_after_property_name' {
  declare module.exports: any;
}

declare module 'scss-lint/lib/linter/space_before_brace' {
  declare module.exports: any;
}

declare module 'scss-lint/lib/linter/space_between_parens' {
  declare module.exports: any;
}

declare module 'scss-lint/lib/linter/string_quotes' {
  declare module.exports: any;
}

declare module 'scss-lint/lib/linter/trailing_semicolon' {
  declare module.exports: any;
}

declare module 'scss-lint/lib/linter/trailing_zero' {
  declare module.exports: any;
}

declare module 'scss-lint/lib/linter/unnecessary_mantissa' {
  declare module.exports: any;
}

declare module 'scss-lint/lib/linter/unnecessary_parent_reference' {
  declare module.exports: any;
}

declare module 'scss-lint/lib/linter/url_format' {
  declare module.exports: any;
}

declare module 'scss-lint/lib/linter/url_quotes' {
  declare module.exports: any;
}

declare module 'scss-lint/lib/linter/variable_for_property' {
  declare module.exports: any;
}

declare module 'scss-lint/lib/linter/vendor_prefixes' {
  declare module.exports: any;
}

declare module 'scss-lint/lib/linter/zero_unit' {
  declare module.exports: any;
}

declare module 'scss-lint/lib/reporter/config' {
  declare module.exports: any;
}

declare module 'scss-lint/lib/reporter/default' {
  declare module.exports: any;
}

declare module 'scss-lint/lib/reporter/files' {
  declare module.exports: any;
}

declare module 'scss-lint/lib/reporter/index' {
  declare module.exports: any;
}

declare module 'scss-lint/lib/reporter/json' {
  declare module.exports: any;
}

declare module 'scss-lint/lib/reporter/xml' {
  declare module.exports: any;
}

declare module 'scss-lint/lib/runner' {
  declare module.exports: any;
}

declare module 'scss-lint/lib/utils' {
  declare module.exports: any;
}

declare module 'scss-lint/test/cli' {
  declare module.exports: any;
}

declare module 'scss-lint/test/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'scss-lint/bin/scss-lint.js' {
  declare module.exports: $Exports<'scss-lint/bin/scss-lint'>;
}
declare module 'scss-lint/lib/cli.js' {
  declare module.exports: $Exports<'scss-lint/lib/cli'>;
}
declare module 'scss-lint/lib/lint.js' {
  declare module.exports: $Exports<'scss-lint/lib/lint'>;
}
declare module 'scss-lint/lib/linter/bang_format.js' {
  declare module.exports: $Exports<'scss-lint/lib/linter/bang_format'>;
}
declare module 'scss-lint/lib/linter/border_zero.js' {
  declare module.exports: $Exports<'scss-lint/lib/linter/border_zero'>;
}
declare module 'scss-lint/lib/linter/color_keyword.js' {
  declare module.exports: $Exports<'scss-lint/lib/linter/color_keyword'>;
}
declare module 'scss-lint/lib/linter/color_variable.js' {
  declare module.exports: $Exports<'scss-lint/lib/linter/color_variable'>;
}
declare module 'scss-lint/lib/linter/comment.js' {
  declare module.exports: $Exports<'scss-lint/lib/linter/comment'>;
}
declare module 'scss-lint/lib/linter/compass_property_with_mixin.js' {
  declare module.exports: $Exports<'scss-lint/lib/linter/compass_property_with_mixin'>;
}
declare module 'scss-lint/lib/linter/compass.js' {
  declare module.exports: $Exports<'scss-lint/lib/linter/compass'>;
}
declare module 'scss-lint/lib/linter/debug_statement.js' {
  declare module.exports: $Exports<'scss-lint/lib/linter/debug_statement'>;
}
declare module 'scss-lint/lib/linter/declaration_order.js' {
  declare module.exports: $Exports<'scss-lint/lib/linter/declaration_order'>;
}
declare module 'scss-lint/lib/linter/duplicate_property.js' {
  declare module.exports: $Exports<'scss-lint/lib/linter/duplicate_property'>;
}
declare module 'scss-lint/lib/linter/else_placement.js' {
  declare module.exports: $Exports<'scss-lint/lib/linter/else_placement'>;
}
declare module 'scss-lint/lib/linter/empty_line_between_blocks.js' {
  declare module.exports: $Exports<'scss-lint/lib/linter/empty_line_between_blocks'>;
}
declare module 'scss-lint/lib/linter/empty_rule.js' {
  declare module.exports: $Exports<'scss-lint/lib/linter/empty_rule'>;
}
declare module 'scss-lint/lib/linter/final_newline.js' {
  declare module.exports: $Exports<'scss-lint/lib/linter/final_newline'>;
}
declare module 'scss-lint/lib/linter/hex_length.js' {
  declare module.exports: $Exports<'scss-lint/lib/linter/hex_length'>;
}
declare module 'scss-lint/lib/linter/hex_notation.js' {
  declare module.exports: $Exports<'scss-lint/lib/linter/hex_notation'>;
}
declare module 'scss-lint/lib/linter/hex_validation.js' {
  declare module.exports: $Exports<'scss-lint/lib/linter/hex_validation'>;
}
declare module 'scss-lint/lib/linter/id_selector.js' {
  declare module.exports: $Exports<'scss-lint/lib/linter/id_selector'>;
}
declare module 'scss-lint/lib/linter/import_path.js' {
  declare module.exports: $Exports<'scss-lint/lib/linter/import_path'>;
}
declare module 'scss-lint/lib/linter/important_rule.js' {
  declare module.exports: $Exports<'scss-lint/lib/linter/important_rule'>;
}
declare module 'scss-lint/lib/linter/indentation.js' {
  declare module.exports: $Exports<'scss-lint/lib/linter/indentation'>;
}
declare module 'scss-lint/lib/linter/index.js' {
  declare module.exports: $Exports<'scss-lint/lib/linter/index'>;
}
declare module 'scss-lint/lib/linter/leading_zero.js' {
  declare module.exports: $Exports<'scss-lint/lib/linter/leading_zero'>;
}
declare module 'scss-lint/lib/linter/mergeable_selector.js' {
  declare module.exports: $Exports<'scss-lint/lib/linter/mergeable_selector'>;
}
declare module 'scss-lint/lib/linter/name_format.js' {
  declare module.exports: $Exports<'scss-lint/lib/linter/name_format'>;
}
declare module 'scss-lint/lib/linter/nesting_depth.js' {
  declare module.exports: $Exports<'scss-lint/lib/linter/nesting_depth'>;
}
declare module 'scss-lint/lib/linter/placeholder_in_extend.js' {
  declare module.exports: $Exports<'scss-lint/lib/linter/placeholder_in_extend'>;
}
declare module 'scss-lint/lib/linter/property_count.js' {
  declare module.exports: $Exports<'scss-lint/lib/linter/property_count'>;
}
declare module 'scss-lint/lib/linter/property_sort_order.js' {
  declare module.exports: $Exports<'scss-lint/lib/linter/property_sort_order'>;
}
declare module 'scss-lint/lib/linter/property_spelling.js' {
  declare module.exports: $Exports<'scss-lint/lib/linter/property_spelling'>;
}
declare module 'scss-lint/lib/linter/qualifying_element.js' {
  declare module.exports: $Exports<'scss-lint/lib/linter/qualifying_element'>;
}
declare module 'scss-lint/lib/linter/selector_depth.js' {
  declare module.exports: $Exports<'scss-lint/lib/linter/selector_depth'>;
}
declare module 'scss-lint/lib/linter/selector_format.js' {
  declare module.exports: $Exports<'scss-lint/lib/linter/selector_format'>;
}
declare module 'scss-lint/lib/linter/shorthand.js' {
  declare module.exports: $Exports<'scss-lint/lib/linter/shorthand'>;
}
declare module 'scss-lint/lib/linter/single_line_per_property.js' {
  declare module.exports: $Exports<'scss-lint/lib/linter/single_line_per_property'>;
}
declare module 'scss-lint/lib/linter/single_line_per_selector.js' {
  declare module.exports: $Exports<'scss-lint/lib/linter/single_line_per_selector'>;
}
declare module 'scss-lint/lib/linter/space_after_comma.js' {
  declare module.exports: $Exports<'scss-lint/lib/linter/space_after_comma'>;
}
declare module 'scss-lint/lib/linter/space_after_property_colon.js' {
  declare module.exports: $Exports<'scss-lint/lib/linter/space_after_property_colon'>;
}
declare module 'scss-lint/lib/linter/space_after_property_name.js' {
  declare module.exports: $Exports<'scss-lint/lib/linter/space_after_property_name'>;
}
declare module 'scss-lint/lib/linter/space_before_brace.js' {
  declare module.exports: $Exports<'scss-lint/lib/linter/space_before_brace'>;
}
declare module 'scss-lint/lib/linter/space_between_parens.js' {
  declare module.exports: $Exports<'scss-lint/lib/linter/space_between_parens'>;
}
declare module 'scss-lint/lib/linter/string_quotes.js' {
  declare module.exports: $Exports<'scss-lint/lib/linter/string_quotes'>;
}
declare module 'scss-lint/lib/linter/trailing_semicolon.js' {
  declare module.exports: $Exports<'scss-lint/lib/linter/trailing_semicolon'>;
}
declare module 'scss-lint/lib/linter/trailing_zero.js' {
  declare module.exports: $Exports<'scss-lint/lib/linter/trailing_zero'>;
}
declare module 'scss-lint/lib/linter/unnecessary_mantissa.js' {
  declare module.exports: $Exports<'scss-lint/lib/linter/unnecessary_mantissa'>;
}
declare module 'scss-lint/lib/linter/unnecessary_parent_reference.js' {
  declare module.exports: $Exports<'scss-lint/lib/linter/unnecessary_parent_reference'>;
}
declare module 'scss-lint/lib/linter/url_format.js' {
  declare module.exports: $Exports<'scss-lint/lib/linter/url_format'>;
}
declare module 'scss-lint/lib/linter/url_quotes.js' {
  declare module.exports: $Exports<'scss-lint/lib/linter/url_quotes'>;
}
declare module 'scss-lint/lib/linter/variable_for_property.js' {
  declare module.exports: $Exports<'scss-lint/lib/linter/variable_for_property'>;
}
declare module 'scss-lint/lib/linter/vendor_prefixes.js' {
  declare module.exports: $Exports<'scss-lint/lib/linter/vendor_prefixes'>;
}
declare module 'scss-lint/lib/linter/zero_unit.js' {
  declare module.exports: $Exports<'scss-lint/lib/linter/zero_unit'>;
}
declare module 'scss-lint/lib/reporter/config.js' {
  declare module.exports: $Exports<'scss-lint/lib/reporter/config'>;
}
declare module 'scss-lint/lib/reporter/default.js' {
  declare module.exports: $Exports<'scss-lint/lib/reporter/default'>;
}
declare module 'scss-lint/lib/reporter/files.js' {
  declare module.exports: $Exports<'scss-lint/lib/reporter/files'>;
}
declare module 'scss-lint/lib/reporter/index.js' {
  declare module.exports: $Exports<'scss-lint/lib/reporter/index'>;
}
declare module 'scss-lint/lib/reporter/json.js' {
  declare module.exports: $Exports<'scss-lint/lib/reporter/json'>;
}
declare module 'scss-lint/lib/reporter/xml.js' {
  declare module.exports: $Exports<'scss-lint/lib/reporter/xml'>;
}
declare module 'scss-lint/lib/runner.js' {
  declare module.exports: $Exports<'scss-lint/lib/runner'>;
}
declare module 'scss-lint/lib/utils.js' {
  declare module.exports: $Exports<'scss-lint/lib/utils'>;
}
declare module 'scss-lint/test/cli.js' {
  declare module.exports: $Exports<'scss-lint/test/cli'>;
}
declare module 'scss-lint/test/utils.js' {
  declare module.exports: $Exports<'scss-lint/test/utils'>;
}
