// flow-typed signature: 2b5fe8dcb8ddbbbf5da77f673ac92af1
// flow-typed version: <<STUB>>/vinyl-named_v1.1.0/flow_v0.52.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'vinyl-named'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'vinyl-named' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'vinyl-named/test/fixtures/one' {
  declare module.exports: any;
}

declare module 'vinyl-named/test/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'vinyl-named/index' {
  declare module.exports: $Exports<'vinyl-named'>;
}
declare module 'vinyl-named/index.js' {
  declare module.exports: $Exports<'vinyl-named'>;
}
declare module 'vinyl-named/test/fixtures/one.js' {
  declare module.exports: $Exports<'vinyl-named/test/fixtures/one'>;
}
declare module 'vinyl-named/test/test.js' {
  declare module.exports: $Exports<'vinyl-named/test/test'>;
}
